// Mocks generated by Mockito 5.4.6 from annotations
// in writer/test/services/sync_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:writer/models/offline_operation.dart' as _i4;
import 'package:writer/models/token_usage.dart' as _i7;
import 'package:writer/repositories/remote_repository.dart' as _i5;
import 'package:writer/services/network_monitor.dart' as _i8;
import 'package:writer/services/offline_queue_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [OfflineQueueService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOfflineQueueService extends _i1.Mock
    implements _i2.OfflineQueueService {
  @override
  _i3.Future<void> enqueue(_i4.OfflineOperation? operation) =>
      (super.noSuchMethod(
            Invocation.method(#enqueue, [operation]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.OfflineOperation>> getPendingOperations() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingOperations, []),
            returnValue: _i3.Future<List<_i4.OfflineOperation>>.value(
              <_i4.OfflineOperation>[],
            ),
            returnValueForMissingStub:
                _i3.Future<List<_i4.OfflineOperation>>.value(
                  <_i4.OfflineOperation>[],
                ),
          )
          as _i3.Future<List<_i4.OfflineOperation>>);

  @override
  _i3.Future<void> markCompleted(String? operationId) =>
      (super.noSuchMethod(
            Invocation.method(#markCompleted, [operationId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> markFailed(String? operationId, String? error) =>
      (super.noSuchMethod(
            Invocation.method(#markFailed, [operationId, error]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> incrementRetry(String? operationId) =>
      (super.noSuchMethod(
            Invocation.method(#incrementRetry, [operationId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> clearCompleted() =>
      (super.noSuchMethod(
            Invocation.method(#clearCompleted, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<int> getPendingCount() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingCount, []),
            returnValue: _i3.Future<int>.value(0),
            returnValueForMissingStub: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<void> removeOperation(String? operationId) =>
      (super.noSuchMethod(
            Invocation.method(#removeOperation, [operationId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [RemoteRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteRepository extends _i1.Mock implements _i5.RemoteRepository {
  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
            returnValueForMissingStub: _i6.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  _i3.Future<dynamic> get(
    String? path, {
    Map<String, dynamic>? queryParameters,
    bool? retryUnauthorized = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [path],
              {
                #queryParameters: queryParameters,
                #retryUnauthorized: retryUnauthorized,
              },
            ),
            returnValue: _i3.Future<dynamic>.value(),
            returnValueForMissingStub: _i3.Future<dynamic>.value(),
          )
          as _i3.Future<dynamic>);

  @override
  _i3.Future<dynamic> post(
    String? path,
    Map<String, dynamic>? body, {
    bool? retryUnauthorized = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [path, body],
              {#retryUnauthorized: retryUnauthorized},
            ),
            returnValue: _i3.Future<dynamic>.value(),
            returnValueForMissingStub: _i3.Future<dynamic>.value(),
          )
          as _i3.Future<dynamic>);

  @override
  _i3.Future<dynamic> patch(
    String? path,
    Map<String, dynamic>? body, {
    bool? retryUnauthorized = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patch,
              [path, body],
              {#retryUnauthorized: retryUnauthorized},
            ),
            returnValue: _i3.Future<dynamic>.value(),
            returnValueForMissingStub: _i3.Future<dynamic>.value(),
          )
          as _i3.Future<dynamic>);

  @override
  _i3.Future<void> delete(
    String? path, {
    Map<String, dynamic>? queryParameters,
    bool? retryUnauthorized = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [path],
              {
                #queryParameters: queryParameters,
                #retryUnauthorized: retryUnauthorized,
              },
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> fetchCharacterProfile(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#fetchCharacterProfile, [name]),
            returnValue: _i3.Future<String?>.value(),
            returnValueForMissingStub: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<String?> convertCharacter({
    required String? name,
    required String? templateContent,
    required String? language,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#convertCharacter, [], {
              #name: name,
              #templateContent: templateContent,
              #language: language,
            }),
            returnValue: _i3.Future<String?>.value(),
            returnValueForMissingStub: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<String?> fetchSceneProfile(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#fetchSceneProfile, [name]),
            returnValue: _i3.Future<String?>.value(),
            returnValueForMissingStub: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<String?> convertScene({
    required String? name,
    required String? templateContent,
    required String? language,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#convertScene, [], {
              #name: name,
              #templateContent: templateContent,
              #language: language,
            }),
            returnValue: _i3.Future<String?>.value(),
            returnValueForMissingStub: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<_i7.TokenUsage?> getCurrentMonthUsage() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentMonthUsage, []),
            returnValue: _i3.Future<_i7.TokenUsage?>.value(),
            returnValueForMissingStub: _i3.Future<_i7.TokenUsage?>.value(),
          )
          as _i3.Future<_i7.TokenUsage?>);

  @override
  _i3.Future<_i7.TokenUsageHistory?> getUsageHistory({
    String? startDate,
    String? endDate,
    int? limit = 100,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getUsageHistory, [], {
              #startDate: startDate,
              #endDate: endDate,
              #limit: limit,
              #offset: offset,
            }),
            returnValue: _i3.Future<_i7.TokenUsageHistory?>.value(),
            returnValueForMissingStub:
                _i3.Future<_i7.TokenUsageHistory?>.value(),
          )
          as _i3.Future<_i7.TokenUsageHistory?>);

  @override
  _i3.Future<String?> getAdminLogs({int? lines = 1000}) =>
      (super.noSuchMethod(
            Invocation.method(#getAdminLogs, [], {#lines: lines}),
            returnValue: _i3.Future<String?>.value(),
            returnValueForMissingStub: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);
}

/// A class which mocks [NetworkMonitor].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkMonitor extends _i1.Mock implements _i8.NetworkMonitor {
  @override
  bool get isOnline =>
      (super.noSuchMethod(
            Invocation.getter(#isOnline),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i3.Stream<bool> get connectivityStream =>
      (super.noSuchMethod(
            Invocation.getter(#connectivityStream),
            returnValue: _i3.Stream<bool>.empty(),
            returnValueForMissingStub: _i3.Stream<bool>.empty(),
          )
          as _i3.Stream<bool>);

  @override
  _i3.Future<bool> get isConnected =>
      (super.noSuchMethod(
            Invocation.getter(#isConnected),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  void startMonitoring() => super.noSuchMethod(
    Invocation.method(#startMonitoring, []),
    returnValueForMissingStub: null,
  );

  @override
  void stopMonitoring() => super.noSuchMethod(
    Invocation.method(#stopMonitoring, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
